version: "3.9"

services:
  jenkins:
    build:
      context: .
    container_name: jenkins-master
    privileged: true
    user: root
    environment:
      - JENKINS_ADMIN_ID=admin
      - JENKINS_ADMIN_PASSWORD=admin123
    ports:
      - "8080:8080"   # Jenkins UI
      - "50000:50000" # Jenkins agent
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # nếu cần chạy docker trong container

volumes:
  jenkins_home:
